name: Database Backup

on:
  schedule:
    - cron: '0 2 * * *' # Daily at 2 AM UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Create backup
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          # Link to project
          supabase link --project-ref $SUPABASE_PROJECT_ID
          
          # Create backup
          DATE=$(date +%Y%m%d_%H%M%S)
          supabase db dump -f "backup_${DATE}.sql"
          
          # Compress backup
          gzip "backup_${DATE}.sql"
          
          # List backup file
          ls -lh backup_*.sql.gz
      
      - name: Upload backup to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: database-backup-${{ github.run_id }}
          path: backup_*.sql.gz
          retention-days: 30
      
      - name: Notify on success
        if: success()
        run: echo "✅ Database backup completed successfully"
      
      - name: Notify on failure
        if: failure()
        run: echo "❌ Database backup failed"